== Lessons

* Renaming classes that are in Git, confuses Git and hence conflicts appear
* Using generics for the DAOs would become a pain in the buttocks if the model becomes more complicated,
since it would be necessary to handle loading, saving, deleting etc. inside the generic DAO

== Course Ideas
* change currency from `String` to enum
* make sure the domain object doesn't leak on the UI
-> use the `Income` object as it is, but do a refactoring before finishing;
perhaps when changing the currency from `String` to enum
* consider breaking the mapping of the test file names with the class they are testing
* add a negative case for when the income cannot be added,
by using a factory to create incomes in controller and adding the business validation in the factory
* the console UI uses the MVC pattern
** the controller holds a reference to a view in order to update it
** if the controller doesn't update the view, it doesn't hold the reference
** the controller updates the model using the values provided by the console UI
* after moving the income functionality to its own package, I realized that the main menu could also
be moved to a separate package, outside the transactions package, since it is common for multiple
functionalities(i.e. expenses)
* the Income and Expense tests are very similar, perhaps a refactoring to use parameterized tests would
be a good idea
* Ask: "Why aren't we using generics just like spring does?" and answer: "Good question, we would get
to reduce our codebase, but then we would have to be able to make sure that more complex models(things like
many-to-many) would still be handled correctly and that is not the purpose for right now, at least"
* currently, the income/expense day is set as a string which holds a number. It might be a good idea to
change it to date and introduce localization with this change
* using a getAll method is not very optimal, since there may be many entries in the data source; however,
for the transactions of a person, this number is usually very small; an improvement would be to hold the
initial balance as a number and increment/decrement that number when a new transaction happens
* present also disadvantages
** e.g. using the initial balance requires loading/storing it every time the app starts/shuts down;
this would require updating all the required places with the aforementioned logic; this can be a potential
source of bugs, since missing one of them could corrupt the balance