== Lessons

* Renaming classes that are in Git, confuses Git and hence conflicts appear

== Course Ideas
* change currency from `String` to enum
* make sure the domain object doesn't leak on the UI
-> use the `Income` object as it is, but do a refactoring before finishing;
perhaps when changing the currency from `String` to enum
* consider breaking the mapping of the test file names with the class they are testing
* add a negative case for when the income cannot be added,
by using a factory to create incomes in controller and adding the business validation in the factory
* the console UI uses the MVC pattern
** the controller holds a reference to a view in order to update it
** if the controller doesn't update the view, it doesn't hold the reference
** the controller updates the model using the values provided by the console UI
* after moving the income functionality to its own package, I realized that the main menu could also
be moved to a separate package, outside the transactions package, since it is common for multiple
functionalities(i.e. expenses)